//! RL-Designer's GitHub repo (ALXS-GitHub/RL-Designer): decal and ball packs
//! already converted to the app's format, under `decals/alxs-rl-mod/`
//! (`index.json` + `<decals|balls>/<Pack>/<Variant>/<files>`), generated by
//! `examples/rl_designer_export.rs`. Only files listed in the index are
//! fetched, from that one path of that one repo.

use std::path::Path;

use serde::{Deserialize, Serialize};
use url::Url;

use crate::base::error::{AppError, AppResult};
use crate::base::security::{self, Purpose};
use crate::market::model::{MarketItem, MarketKind, MarketPage, MarketSource};

pub const RAW_BASE: &str =
    "https://raw.githubusercontent.com/ALXS-GitHub/RL-Designer/main/decals/alxs-rl-mod";
const TREE_BASE: &str = "https://github.com/ALXS-GitHub/RL-Designer/tree/main/decals/alxs-rl-mod";
const MAX_TOTAL_BYTES: usize = 128 * 1024 * 1024;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Index {
    pub version: u32,
    pub packs: Vec<IndexPack>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct IndexPack {
    pub kind: MarketKind,
    pub name: String,
    #[serde(default)]
    pub group: Option<String>,
    pub variants: Vec<IndexVariant>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct IndexVariant {
    pub name: String,
    pub files: Vec<String>,
    #[serde(default)]
    pub preview: Option<String>,
}

pub fn kind_dir(kind: MarketKind) -> &'static str {
    match kind {
        MarketKind::Decal => "decals",
        MarketKind::Ball => "balls",
    }
}

/// A path segment taken from the index: one plain name, never a path.
fn safe_segment(s: &str) -> bool {
    !s.is_empty()
        && s != "."
        && s != ".."
        && !s.contains(['/', '\\', ':'])
        && !s.chars().any(char::is_control)
}

fn url_of(base: &str, segments: &[&str]) -> AppResult<Url> {
    if !segments.iter().all(|s| safe_segment(s)) {
        return Err(AppError::InvalidInput(format!(
            "unsafe path in the RL-Designer index: {segments:?}"
        )));
    }
    let mut url = Url::parse(base).map_err(|e| AppError::Internal(e.to_string()))?;
    url.path_segments_mut()
        .map_err(|()| AppError::Internal("base url".into()))?
        .extend(segments);
    Ok(url)
}

fn file_url(kind: MarketKind, pack: &str, variant: &str, file: &str) -> AppResult<Url> {
    url_of(RAW_BASE, &[kind_dir(kind), pack, variant, file])
}

async fn get(url: &Url) -> AppResult<reqwest::Response> {
    security::ensure_allowed(url.as_str(), Purpose::Market)?;
    Ok(security::http_client(Purpose::Market)?
        .get(url.clone())
        .send()
        .await?
        .error_for_status()?)
}

pub async fn fetch_index() -> AppResult<Index> {
    let url = url_of(RAW_BASE, &["index.json"])?;
    let index: Index = get(&url).await?.json().await?;
    Ok(index)
}

pub fn items(index: &Index, kind: MarketKind, query: &str) -> Vec<MarketItem> {
    let q = query.trim().to_lowercase();
    index
        .packs
        .iter()
        .filter(|p| p.kind == kind && safe_segment(&p.name))
        .filter(|p| {
            q.is_empty()
                || p.name.to_lowercase().contains(&q)
                || p.group
                    .as_ref()
                    .is_some_and(|g| g.to_lowercase().contains(&q))
        })
        .map(|p| {
            let thumbnail = p.variants.first().and_then(|v| {
                let file = v
                    .preview
                    .as_deref()
                    .or(v.files.first().map(String::as_str))?;
                file_url(kind, &p.name, &v.name, file)
                    .ok()
                    .map(String::from)
            });
            MarketItem {
                source: MarketSource::RlDesigner,
                id: p.name.clone(),
                kind,
                title: p.name.clone(),
                author: Some("RL-Designer".into()),
                description: p.group.clone(),
                thumbnail,
                page_url: url_of(TREE_BASE, &[kind_dir(kind), &p.name])
                    .ok()
                    .map(String::from),
                downloads: None,
                likes: None,
                bodies: p.variants.iter().map(|v| v.name.clone()).collect(),
                ready: true,
                installed: false,
            }
        })
        .collect()
}

pub async fn browse(kind: MarketKind, query: &str) -> AppResult<MarketPage> {
    let index = fetch_index().await?;
    let items = items(&index, kind, query);
    Ok(MarketPage {
        total: Some(items.len() as u64),
        truncated: false,
        items,
    })
}

/// Downloads every file of the pack into `dest/<Pack>/<Variant>/`.
pub async fn download_pack(kind: MarketKind, name: &str, dest: &Path) -> AppResult<()> {
    let index = fetch_index().await?;
    let pack = index
        .packs
        .iter()
        .find(|p| p.kind == kind && p.name == name)
        .ok_or_else(|| AppError::NotFound(format!("RL-Designer pack {name}")))?;
    let mut total = 0usize;
    for v in &pack.variants {
        let dir = dest.join(&pack.name).join(&v.name);
        std::fs::create_dir_all(&dir)?;
        for file in &v.files {
            let url = file_url(kind, &pack.name, &v.name, file)?;
            let bytes = get(&url).await?.bytes().await?;
            total += bytes.len();
            if total > MAX_TOTAL_BYTES {
                return Err(AppError::InvalidInput("pack larger than 128 MB".into()));
            }
            std::fs::write(dir.join(file), &bytes)?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn index() -> Index {
        serde_json::from_str(
            r#"{"version":1,"packs":[
              {"kind":"decal","name":"Born To Be Itzy","group":"Itzy","variants":[
                {"name":"Octane","files":["Template.json","hybrid_art.png"],"preview":"hybrid_art.png"},
                {"name":"Fennec","files":["Template.json"]}]},
              {"kind":"ball","name":"Aespa","variants":[{"name":"Default","files":["Template.json","diffuse.png"]}]},
              {"kind":"decal","name":"../evil","variants":[]}
            ]}"#,
        )
        .unwrap()
    }

    #[test]
    fn lists_packs_by_kind_and_query() {
        let decals = items(&index(), MarketKind::Decal, "");
        assert_eq!(decals.len(), 1, "unsafe names are dropped");
        let d = &decals[0];
        assert_eq!(d.bodies, ["Octane", "Fennec"]);
        assert!(d.ready);
        assert_eq!(
            d.thumbnail.as_deref(),
            Some(
                "https://raw.githubusercontent.com/ALXS-GitHub/RL-Designer/main/decals/alxs-rl-mod/decals/Born%20To%20Be%20Itzy/Octane/hybrid_art.png"
            )
        );
        assert_eq!(items(&index(), MarketKind::Decal, "itzy").len(), 1);
        assert!(items(&index(), MarketKind::Decal, "aespa").is_empty());
        assert_eq!(items(&index(), MarketKind::Ball, "").len(), 1);
    }

    #[test]
    fn refuses_paths_in_index_names() {
        assert!(file_url(MarketKind::Decal, "Pack", "Octane", "../../x.png").is_err());
        assert!(file_url(MarketKind::Decal, "Pack", "..", "x.png").is_err());
        assert!(file_url(MarketKind::Decal, "Pack", "Octane", "a\\b.png").is_err());
    }
}
